### ISSUE TITLE
CAMPHORsomatic depends on python3 but all invocations of python call `python`

### ISSUE THREAD

**Issue by oneillkza** [afujimoto/CAMPHORsomatic#1]
On dual-python systems (as are still fairly common), the standard is as follows:
```
python -> python2
python3 -> python3
```
However, `CAMPHOR_SVcall.sh` calls `python` when it actually requires `python3`. 

This causes errors like below:

```
samtools view ./example/sample1.sort_by_name.test.bam|python ./src/read_format.py /dev/stdin 100 0.3|python ./src/SV_format.py /dev/stdin 0.05 100 0 10 0.3 1000 20 > sample1/SV_read.txt
  File "./src/SV_format.py", line 77
    print("NA", "NA", seq_align_pos[0][3], str(seq_align_pos[0][4]), "BR", str(mapping_start_on_read), seq[0:mapping_start_on_read + 1], line, sep="\t")
                                                                                                                                                  ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "./src/read_format.py", line 179, in <module>
    print ("\t".join(out))
IOError: [Errno 32] Broken pipe
```

You should modify the script to use `python3` instead of `python`, and also mention that python3 is a requirement in your documentation.

**Comment by afujimoto** [comment]
Thank you for this comment. We corrected our scripts.
