### ISSUE TITLE
CAMPHOR_SVcall.sh IndexError: list index out of range

### ISSUE THREAD

**Issue by wnakamur505** [afujimoto/CAMPHORsomatic#5]
Dear 
Prof. Akihiro Fujimoto

I tried to run `CAMPHOR_SVcall.sh` on the following cell lines.
・ HCC1954
・ HCC1954BL
・ COLO829BL
The same error below is output in three cases. What is the cause of this error? 
I hope you'll tell me.

```
Traceback (most recent call last):
 File "./src/SV_support_read.2.py", line 270, in <module>
  distance = get_distance(breakpoint_tmp_l[3])
 File "./src/SV_support_read.2.py", line 215, in get_distance
  if max_len < int(read_tmp_l[9]):
IndexError: list index out of range

```

Regards

Nakamura

**Comment by afujimoto** [comment]
Dear Dr. Nakamura

Thank you for your message.

(1) Could you run the example on the readme page?
(2) ./src/SV_support_read.2.py reads SV_read.txt.2 file. Could you please check the SV_read.txt.2 file. If you can send me the SV_read.txt.2 file or the input bam files, I can check them.

Regards,

Akihiro

**Comment by wnakamur505** [comment]
Dear Prof. Akihiro Fujimoto
Thank you for your reply. 

(1) Could you run the example on the readme page?
> Yes, I could run the example on the readme page and get the SV/somatic_SV.vcf file without any errors.

(2) ./src/SV_support_read.2.py reads SV_read.txt.2 file. Could you please check the SV_read.txt.2 file. If you can send me the SV_read.txt.2 file or the input bam files, I can check them.
> I would appreciate it if you could tell me if there is anything wrong, but the size of SV_read.txt.2 file is very large.
Could this error depend on the minimap2 options?

Regards,

Nakamura

**Comment by wnakamur505** [comment]
Dear Prof. Akihiro Fujimoto
Thank you for your reply. 

(1) Could you run the example on the readme page?
> Yes, I could run the example on the readme page and get the SV/somatic_SV.vcf file without any errors.

(2) ./src/SV_support_read.2.py reads SV_read.txt.2 file. Could you please check the SV_read.txt.2 file. If you can send me the SV_read.txt.2 file or the input bam files, I can check them.
> I would appreciate it if you could tell me if there is anything wrong, but the size of SV_read.txt.2 file is very large.
Could this error depend on the minimap2 options?

Regards,

Nakamura

**Comment by afujimoto** [comment]
Dear Dr. Nakamura

Thank you for your reply.

> (2) ./src/SV_support_read.2.py reads SV_read.txt.2 file. Could you please check the SV_read.txt.2 file. If you can send me the SV_read.txt.2 file or the input bam files, I can check them.
> 
> I would appreciate it if you could tell me if there is anything wrong, but the size of SV_read.txt.2 file is very large.
> Could this error depend on the minimap2 options?
> 
> 


I run minimap2 with the following command. 
minimap2 -a -g2000 -A1 -B2 -O2,32 -E1,0 -z200 REF fastq

I think that the error may not be caused by the option of minimap2.

(1) Can I get fastq file that you have analyzed?
I think that I can receive the fastq file via google drive. If you can give me the file, I will prepare a folder in google drive.

(2) Please check the output files.
SV_support_read.2.py uses to generate 4 files (DEL_candidate.txt, CHR_candidate.txt, INV_candidate.txt, and TRS_candidate.txt).
Are these files generated? Which is the newest file?

I am sorry for the inconvenience.
I look forward to your reply.

Regards,

Akihiro

**Comment by wnakamur505** [comment]
Dear Prof. Akihiro Fujimoto
Thank you for your reply.
I am very sorry for the late reply.

I run minimap2 with the following command.
minimap2 -a -g2000 -A1 -B2 -O2,32 -E1,0 -z200 REF fastq

> I performed minimap2 with the following command according to your message with COLO cell line.
minimap2 -ax map-ont -t 8 -a -g2000 -A1 -B2 -O2,32 -E1,0 -z200 REF fastq
After that, I performed CAMPHOR_SVcall.sh and finished without errors. I don't know why this happened.
I will run minimap2 to another fastq file, and also try to perform CAMPHOR_comparison.sh.

(1) Can I get fastq file that you have analyzed?
I think that I can receive the fastq file via google drive. If you can give me the file, I will prepare a folder in google drive.
>  I will ask my boss.

(2) Please check the output files.
SV_support_read.2.py uses to generate 4 files (DEL_candidate.txt, CHR_candidate.txt, INV_candidate.txt, and TRS_candidate.txt).
Are these files generated? Which is the newest file?
> The newest one is  "DEL_candidate.txt".

Regards,

Nakamura
